import Link from 'next/link';
import { Button } from '@/components/ui/button';
import PublicHeader from '@/components/shared/public-header';
import { Calculator } from 'lucide-react';
import ThemeToggle from '@/components/shared/theme-toggle';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AdaptWeb Cost Calculator | Terms of Service',
  description: 'Professional Website Estimation & Lead Management Platform.',
};

export const revalidate = 3600; // Cache for 1 hour

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans relative overflow-hidden transition-colors duration-300">
      {/* Background Gradients & Grid Overlay */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,var(--border)_1px,transparent_1px),linear-gradient(to_bottom,var(--border)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-20 dark:opacity-40 pointer-events-none" />
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-indigo-500/5 rounded-full blur-[120px] pointer-events-none" />

      {/* Navbar Header */}
      <PublicHeader />

      {/* Main Content */}
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 space-y-8 relative z-10">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground">
            Service rules, quotation approximations disclaimer, and user conditions.
          </p>
        </div>

        <div className="p-8 rounded-3xl border border-border bg-card/40 backdrop-blur-sm max-w-none text-foreground text-sm space-y-6 leading-relaxed shadow-sm">
          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">1. Service Usage</h3>
            <p className="text-muted-foreground">
              By accessing the AdaptWeb Cost Calculator, you agree to be bound by these Terms of Service. This platform is provided for business estimation and project planning purposes. You agree to use the service in compliance with all applicable laws.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">2. Estimate Disclaimer</h3>
            <p className="text-muted-foreground">
              All prices generated by the cost calculator wizard are estimates based on standard agency benchmarks. They are approximate and do not represent a final binding service contract or bid commitment. Final pricing may change after a formal project consultation to accommodate bespoke requirements.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">3. Account Responsibilities</h3>
            <p className="text-muted-foreground">
              Users registering profiles are responsible for maintaining the confidentiality of their authentication credentials. Generating excessive mock evaluations aimed at stressing server APIs is strictly prohibited.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">4. Proposal Validity</h3>
            <p className="text-muted-foreground">
              Quotations created on-demand are valid for the timeframe configured in settings (usually 30 days) from the date of generation, unless superseded by a formal written proposal from AdaptWeb IT Solutions.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">5. Payment Terms</h3>
            <p className="text-muted-foreground">
              Generating estimates on this platform is free. Any actual project development services requested following an estimate will be subject to a separate, formal Master Services Agreement and associated payment schedules.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">6. Intellectual Property</h3>
            <p className="text-muted-foreground">
              All content, algorithms, calculation formulas, designs, and software underlying the AdaptWeb Cost Calculator are the intellectual property of AdaptWeb IT Solutions.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">7. Limitation of Liability</h3>
            <p className="text-muted-foreground">
              AdaptWeb IT Solutions shall not be held liable for any indirect, incidental, or consequential damages resulting from the use of, or inability to use, the platform or the reliance on generated estimates.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">8. Termination</h3>
            <p className="text-muted-foreground">
              We reserve the right to suspend or terminate user accounts that violate these Terms of Service or engage in abusive platform behavior, at our sole discretion.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="text-base font-bold text-primary uppercase tracking-wider">9. Contact</h3>
            <p className="text-muted-foreground">
              If you have any questions regarding these Terms, please contact AdaptWeb IT Solutions through our primary contact channels.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="mt-auto border-t border-border bg-card py-8 text-center text-xs text-muted-foreground">
        <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p>© {new Date().getFullYear()} AdaptWeb Cost Calculator. An AdaptWeb Product.</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-foreground transition-colors font-medium">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors font-medium">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
